name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ">= 17.0.0"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies and build 🔧
        run: yarn install --frozen-lockfile && yarn build
      - name: Set version
        run: npm version $(echo "${{ github.event.release.tag_name }}" | sed "s/v//") --no-git-tag-version
      - name: Publish package on NPM 📦
        run: npm publish --provenance --access public
